apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Values.image.tag }}
    app.kubernetes.io/managed-by: github
    app.kubernetes.io/component: pod
    app.kubernetes.io/part-of: {{ .Release.Name }}-svc
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: "{{ .Values.image.registry }}/{{ .Values.image.repo }}:{{ .Values.image.tag }}"
        env: 
        {{- include "environments" . | indent 8 }}
        {{- if .Values.limitsEnabled }}
        resources:
          limits:
            memory: {{ .Values.app.resources.limits.memory | quote }}
            cpu: {{ .Values.app.resources.limits.cpu | quote }}
          requests:
            memory: {{ .Values.app.resources.requests.memory | quote }}
            cpu: {{ .Values.app.resources.requests.cpu | quote }}
        {{- end }}
        ports:
        - containerPort: 8080
        {{- if .Values.probeEnabled }}
        livenessProbe:
          httpGet:
            path:  {{ .Values.livenessProbe.httpGet.path | quote }}
            port:  {{ .Values.livenessProbe.httpGet.port }}
          initialDelaySeconds:  {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds:  {{ .Values.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          successThreshold: {{ .Values.livenessProbe.successThreshold }}
        readinessProbe:
          httpGet:
            path:  {{ .Values.readinessProbe.httpGet.path | quote }}
            port:  {{ .Values.readinessProbe.httpGet.port }}
          initialDelaySeconds:  {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds:  {{ .Values.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          successThreshold: {{ .Values.readinessProbe.successThreshold }}
        {{- end }}